
/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/

/*
Description: leave type  record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE_TYPE(
LEAVE_TYPE_ID INT(11),
LEAVE_TYPE VARCHAR(100),
PRIMARY KEY(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE_TYPE end*/

/*
Description: leave record
*/
CREATE TABLE IF NOT EXISTS AB_CICD_LEAVE(
LEAVE_ID INT(11),
LEAVE_TYPE_ID INT(11),
EMPLOYEE_NAME VARCHAR(100),
PRIMARY KEY(LEAVE_ID),
FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES AB_CICD_LEAVE_TYPE(LEAVE_TYPE_ID)
);

/*AB_CICD_LEAVE end*/
